### ISSUE TITLE
Season/Episode number offset

### ISSUE THREAD

**Issue by rsdig** [vanowm/airdates.tv_enhancer#1]
The season/episode # offset setting doesn't appear as an option on shows that are showing episode number overall (American Horror Story, Medici, Survivor, The Terror etc.) 
Very little chance of correcting the issue on WIkipedia. Their season numbers are unparseable because the season pages used in the "list of ... episodes" sublist are titled as that seasons name rather than the standard number of the season.
Most shows use eg. "Grey's Anatomy (season 1)" but with anthology shows the season page is always titled using that seasons name rather than its number for example "American Horror Story: Murder House" so the parser reads only number overall presumably because there's no season number in the season titles.

**Comment by vanowm** [comment]
For such shows your best bet is to use "custom show" feature. There is no point of "offset" episode number when season number is not available.
