### ISSUE TITLE
Installation error - Windows Script Host

### ISSUE THREAD

**Issue by DarkQuietduck** [vanowm/airdates.tv_enhancer#2]
![image](https://user-images.githubusercontent.com/60543081/73592197-fec29f80-44f7-11ea-879f-654b96eb3706.png)

Hey, when I try installing the script this error pops up. Can you help?

**Comment by vanowm** [comment]
It seems you downloaded the .js file on your computer and tried "execute" it, it's not how it's done.
You must first install an [userscript manager extension](https://greasyfork.org/en/help/installing-user-scripts) in your browser, than you can install the [script](https://greasyfork.org/en/scripts/28787-airdates-tv-enhancer) by clicking on install button.
